on:
  push:
    branches:
      - '*'
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DB_HOST: localhost
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest clicker_test.py
